from __future__ import annotations

from config.palette import GESTURE_COLORS
from config.strings import (
    GESTURE_CLOSED_FIST,
    GESTURE_I_LOVE_YOU,
    GESTURE_NAMES,
    GESTURE_NONE,
    GESTURE_OPEN_PALM,
    GESTURE_POINTING_UP,
    GESTURE_THUMB_DOWN,
    GESTURE_THUMB_UP,
    GESTURE_VICTORY,
    GESTURES,
)

__all__ = [
    "GESTURES",
    "GESTURE_NAMES",
    "GESTURE_COLORS",
    "GESTURE_NONE",
    "GESTURE_CLOSED_FIST",
    "GESTURE_OPEN_PALM",
    "GESTURE_POINTING_UP",
    "GESTURE_THUMB_DOWN",
    "GESTURE_THUMB_UP",
    "GESTURE_VICTORY",
    "GESTURE_I_LOVE_YOU",
]
